version: '3.8'
services:

  client-prod:
    # restart: always
    build:
      context: ./client
      dockerfile: Dockerfile-production
    ports:
      - "80:80"
    depends_on:
      - server-prod
    volumes_from:
      - server-prod:ro

  server-prod:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile-production
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - db-prod
    volumes:
      - /var/www/html/images:/var/www/html/images

  db-prod:
    restart: always
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=internet_shop_db
    # ports:
    #   - "5432:5432"  
    # volumes:
    #       - data:/var/lib/postgres/data  
volumes:
  server-prod:
  nginx-server-prod:
