const ACTION_TYPES ={
  LOGIN_REQUEST:'auth/loginRequest',
  SIGN_UP_REQUEST:'auth/signUpRequest',
  REFRESH_REQUEST:'auth/refreshRequest',
  CLEAR_USER_STORE: 'CLEAR_USER_STORE',
  AUTH_SUCCESS:'auth/success',
  AUTH_ERROR:'auth/error',

  CATEGORY_GET_REQUEST: 'CATEGORY_GET_REQUES',
  CATEGORY_GET_SUCCESS: 'CATEGORY_GET_SUCCESS',
  CATEGORY_GET_ERROR: 'CATEGORY_GET_ERROR',

  CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUES',
  CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
  CATEGORY_CREATE_ERROR: 'CATEGORY_CREATE_ERROR',

  CATEGORY_DELETE_REQUEST: 'CATEGORY_DELETE_REQUES',
  CATEGORY_DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
  CATEGORY_DELETE_ERROR: 'CATEGORY_DELETE_ERROR',

  CATEGORY_UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUES',
  CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
  CATEGORY_UPDATE_ERROR: 'CATEGORY_UPDATE_ERROR',

  PRODUCT_GET_REQUEST: 'PRODUCT_GET_REQUES',
  PRODUCT_GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
  PRODUCT_GET_ERROR: 'PRODUCT_GET_ERROR',

  PRODUCT_GET_BY_ID_REQUEST: 'PRODUCT_GET_BY_ID_REQUES',
  PRODUCT_GET_BY_ID_SUCCESS: 'PRODUCT_GET_BY_ID_SUCCESS',
  PRODUCT_GET_BY_ID_ERROR: 'PRODUCT_GET_BY_ID_ERROR',

  PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUES',
  PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_ERROR: 'PRODUCT_CREATE_ERROR',

  PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUES',
  PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_ERROR: 'PRODUCT_UPDATE_ERROR',
  }
  
  export default ACTION_TYPES