const ACTION_TYPES ={
  LOGIN_REQUEST:'auth/loginRequest',
  SIGN_UP_REQUEST:'auth/signUpRequest',
  REFRESH_REQUEST:'auth/refreshRequest',
  CLEAR_USER_STORE: 'CLEAR_USER_STORE',
  AUTH_SUCCESS:'auth/success',
  AUTH_ERROR:'auth/error',

  CATEGORY_GET_REQUEST: 'CATEGORY_GET_REQUES',
  CATEGORY_GET_SUCCESS: 'CATEGORY_GET_SUCCESS',
  CATEGORY_GET_ERROR: 'CATEGORY_GET_ERROR',

  CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUES',
  CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
  CATEGORY_CREATE_ERROR: 'CATEGORY_CREATE_ERROR',

  PRODUCT_GET_REQUEST: 'PRODUCT_GET_REQUES',
  PRODUCT_GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
  PRODUCT_GET_ERROR: 'PRODUCT_GET_ERROR',

  PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUES',
  PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_ERROR: 'PRODUCT_CREATE_ERROR',
  }
  
  export default ACTION_TYPES