FROM node:16-alpine

ARG NODE_ENV="production"

# RUN mkdir ./server

# RUN mkdir -p /var/www/html/images/


WORKDIR /server

COPY package*.json ./
COPY package-lock.json ./

RUN npm install -g sequelize-cli

RUN npm install

COPY . .

EXPOSE 5000

RUN npm run build

CMD sequelize db:migrate && sequelize db:seed:all && node ./dist/server.js
